# Generated by Django 4.0 on 2024-07-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buyingoptions_alter_product_image_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_options', to='myapp.product'),
        ),
    ]
