# Generated by Django 4.0 on 2024-08-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_category_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyingoptions',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='buying_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buying_options', to='myapp.buyingoptions'),
        ),
    ]
