# Generated by Django 4.0 on 2024-08-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_buyingoptions_product_product_buying_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buying_option',
        ),
        migrations.AddField(
            model_name='product',
            name='buying_options',
            field=models.ManyToManyField(related_name='products', to='myapp.BuyingOptions'),
        ),
    ]
